### ISSUE TITLE
compatibility with connector?

### ISSUE THREAD

**Issue by mateus3c** [uku3lig/armor-hud#1]
Could you make a compatibility patch for the connector so forge players can also play with your mod?
ukulib and uku's Armor HUD crashes before the game start. thank you!
[uku_armor_hud.log](https://github.com/uku3lig/armor-hud/files/12910983/uku_armor_hud.log)
[uku_armor_hud.-.CONSOLE.log](https://github.com/uku3lig/armor-hud/files/12910984/uku_armor_hud.-.CONSOLE.log)

**Comment by uku3lig** [comment]
fixed upstream
