### ISSUE TITLE
Warning Indicator Broken In 1.20.2+

### ISSUE THREAD

**Issue by Rylanets** [uku3lig/armor-hud#2]
In 0.4.1+ versions of uku's Armor HUD, instead of the warning indicator going over the piece of armor that is on low durability, it goes above the piece of armor furthest on the right when the 'Show Widget: Not Empty' is selected. The animation is also broken where instead of bobbing slowly up and down it just cuts between up and down. I noticed the issue in the 1.20.2 version, but it seems like it also appears in the 1.20.3-1.20.4 version as well.
![item inticatior](https://github.com/uku3lig/armor-hud/assets/156556059/4e439c87-62ea-44ff-a0cb-50f14953ba66)

**Comment by ghost** [comment]
Can confirm on 1.20.4.

**Comment by uku3lig** [comment]
fixed in 0.4.4 https://modrinth.com/mod/ukus-armor-hud/version/inle1PJL

sorry for taking so long, github decided not to send me notifications for this repo...
