### ISSUE TITLE
1.20.6 ?

### ISSUE THREAD

**Issue by Latino2k7** [uku3lig/armor-hud#3]
can you update the mod to the latest version please and thx

**Comment by ghost** [comment]
@uku3lig Any updates on this? I too would like this to be updated!

**Comment by uku3lig** [comment]
https://modrinth.com/mod/ukus-armor-hud/version/DDwWClw8

**Comment by ghost** [comment]
Thank you!

**Comment by Latino2k7** [comment]
Thank you!
