### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by Dourmi** [uku3lig/armor-hud#6]
hey! could it be possible to move the hud more in the left? it would be cool... 
![image](https://github.com/user-attachments/assets/a3f76ab5-a005-4270-8ac2-f1b639d4b2aa)
its not very beautiful with inventorio's off hand

**Comment by uku3lig** [comment]
hello! there are already existing options in the config screen to adjust the vertical and horizontal offset of the armor hud!

**Comment by Dourmi** [comment]
Could you show me please?

**Comment by uku3lig** [comment]
go to options, then click on the uku button and find uku's armor hud. you can configure the mod from there

![image](https://github.com/user-attachments/assets/5c13c1d4-d304-4041-8b65-419cc4abebcd)

alternatively, you can also just go to modmenu and find the mod there

**Comment by Dourmi** [comment]
Thanks! Merry Christmas by the way

**Comment by uku3lig** [comment]
merry christmas and happy holidays!
